window_prefix: wm-

panes:
  - command: nvim .
    focus: true
  - command: <agent>
    split: horizontal
  - split: vertical
    size: 15

files:
  symlink:
    - node_modules

agent: claude
nerdfont: true
